spring:
  application:
    name: eureka
  cloud:
    config:
      enabled: false
server:
  port: 8761
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0